# Generated by Django 4.2.2 on 2023-07-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
