# Generated by Django 4.2.2 on 2023-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
