# Generated by Django 4.2.2 on 2023-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_rentalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='rental_amount',
            field=models.IntegerField(null=True),
        ),
    ]
