# Generated by Django 4.2.2 on 2023-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_rentalhistory_rental_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
