# Generated by Django 4.2.2 on 2023-07-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_rentalhistory_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rentals', to='car.car'),
        ),
    ]
