# Generated by Django 4.2.2 on 2023-07-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_rentalhistory_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
